global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Raven.Client.Documents;
global using Ecommerce.Infraestructure.CrossCutting.Options;
global using Microsoft.Extensions.Options;
global using Ecommerce.Domain.Core.Interfaces.Repositories;
global using Ecommerce.Domain.Models;
global using Raven.Client.Documents.Session;
global using Ecommerce.Infraestructure.Data.Repositories;